// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('ericruisApp').controller('InstructorCtrl', function($q, $scope, $sce, Instructor, Teachers) {
  var embeddedVersion, init, scope;
  scope = $scope;
  $q.all([Instructor, Teachers]).then(function(response) {
    return init(response[0], response[1]);
  });
  init = function(instructors, teachers) {
    var instructorInfo;
    instructorInfo = instructors[0];
    _.each(['name', 'coverPhotoUrl', 'teacherBio', 'firstName'], function(attr) {
      return scope[attr] = instructorInfo.get(attr);
    });
    scope.videoUrl = $sce.trustAsResourceUrl(embeddedVersion(instructorInfo.get('videoUrl')));
    return scope.teachers = teachers;
  };
  return embeddedVersion = function(url) {
    if (_(url).contains('youtube') && !_(url).contains('embed')) {
      return url.replace('watch?v=', 'embed/');
    } else {
      return url;
    }
  };
});
