// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('ericruisApp').controller('InstructorCtrl', function($scope, $sce, Instructor) {
  var embeddedVersion, init, scope;
  scope = $scope;
  Instructor.then(function(response) {
    return init(response[0]);
  });
  init = function(teacherInfo) {
    _.each(['name', 'coverPhotoUrl', 'teacherBio', 'firstName'], function(attr) {
      return scope[attr] = teacherInfo.get(attr);
    });
    return scope.videoUrl = $sce.trustAsResourceUrl(embeddedVersion(teacherInfo.get('videoUrl')));
  };
  return embeddedVersion = function(url) {
    if (_(url).contains('youtube') && !_(url).contains('embed')) {
      return url.replace('watch?v=', 'embed/');
    } else {
      return url;
    }
  };
});
