// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('ericruisApp').controller('MainCtrl', function($scope) {
  return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
});
