// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('ericruisApp').controller('MainCtrl', function($scope, instructors) {
  return instructors.then(function(response) {
    instructors = response;
    return $scope.instructors = instructors;
  });
});
