// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('ericruisApp').factory('instructors', function($q, Parse) {
  var User, deferred, query;
  User = Parse.Object.extend('User');
  query = new Parse.Query(User);
  query.exists('imageURL').equalTo('isTeacher', true).find().then(function(response) {
    return deferred.resolve(response);
  });
  deferred = $q.defer();
  return deferred.promise;
});
