// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('ericruisApp').service('Instructor', function($q, $routeParams, Parse) {
  var User, deferred, instructorId, query;
  instructorId = $routeParams.instructorId;
  User = Parse.Object.extend('User');
  query = new Parse.Query(User);
  query.equalTo('objectId', instructorId);
  query.find().then(function(response) {
    return deferred.resolve(response);
  });
  deferred = $q.defer();
  return deferred.promise;
});
