// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('ericruisApp').factory('instructors', function($q, parse) {
  var User, deferred, query;
  User = parse.Object.extend('User');
  query = new parse.Query(User);
  query.exists('coverPhotoUrl').find().then(function(response) {
    return deferred.resolve(response);
  });
  deferred = $q.defer();
  return deferred.promise;
});
