// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('ericruisApp').service('Teachers', function($q, Parse, Instructor) {
  var deferred;
  Instructor.then(function(response) {
    var SFLineage, instructor, query;
    instructor = response[0];
    SFLineage = Parse.Object.extend("SFLineage");
    query = new Parse.Query(SFLineage);
    return query.equalTo('student', instructor).find().then(function(relations) {
      var teachers;
      teachers = [];
      return _.each(relations, function(relation) {
        return relation.get('teacher').fetch().then(function(teacher) {
          teachers.push(teacher);
          if (teachers.length === relations.length) {
            return deferred.resolve(teachers);
          }
        });
      });
    });
  });
  deferred = $q.defer();
  return deferred.promise;
});
