// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('ericruisApp', ['ngCookies', 'ngResource', 'ngSanitize', 'ngRoute']).config(function($routeProvider) {
  return $routeProvider.when('/', {
    templateUrl: 'views/main.html',
    controller: 'MainCtrl'
  }).when('/sphere', {
    templateUrl: 'views/sphere.html'
  }).otherwise({
    redirectTo: '/'
  });
});
