// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('ericruisApp').directive('three', function() {
  return {
    template: '<div id="canvas-container"></div>',
    restrict: 'E',
    replace: true,
    link: function(scope, element, attrs) {
      var animate, camera, renderer, scene, sprite;
      camera = new THREE.PerspectiveCamera(75, 1, 1, 100);
      camera.position.z = 500;
      scene = new THREE.Scene();
      renderer = new THREE.CSS3DRenderer();
      renderer.setSize(window.innerWidth, window.innerHeight);
      renderer.domElement.style.position = 'absolute';
      sprite = document.createElement('img');
      sprite.src = 'images/yantra.png';
      sprite.addEventListener('load', function(event) {
        var canvas, context, object;
        canvas = document.createElement('canvas');
        canvas.width = sprite.width;
        canvas.height = sprite.height;
        context = canvas.getContext('2d');
        context.drawImage(sprite, 0, 0);
        object = new THREE.CSS3DSprite(canvas);
        return scene.add(object);
      });
      element.append(renderer.domElement);
      animate = (function(_this) {
        return function() {
          requestAnimationFrame(animate);
          return renderer.render(scene, camera);
        };
      })(this);
      return animate();
    }
  };
});
